# Generated by Django 2.2.1 on 2019-08-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('state', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('feature', models.TextField()),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='detect_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('writer', models.CharField(default='admin', max_length=20)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='free_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('writer', models.CharField(default='admin', max_length=20)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=20)),
                ('supporter', models.CharField(default='', max_length=20)),
                ('money', models.IntegerField(default=0)),
                ('status', models.BooleanField(default='False')),
            ],
        ),
    ]
