# Generated by Django 2.2.1 on 2019-08-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detect_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('writer', models.CharField(default='admin', max_length=20)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
