# Generated by Django 2.2.6 on 2019-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
