# Generated by Django 2.2.3 on 2019-08-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
