# Generated by Django 2.2.6 on 2019-10-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_support_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='username',
            new_name='user',
        ),
    ]
