# Generated by Django 2.2.3 on 2019-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.BooleanField(default='true'),
        ),
    ]
