# Generated by Django 2.2.3 on 2019-08-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190810_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='supporter',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
