# Generated by Django 2.2.3 on 2019-08-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190810_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='user_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
