# Generated by Django 2.2.3 on 2019-08-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_support_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='user_id',
        ),
    ]
