# Generated by Django 2.2.3 on 2019-08-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_support_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='user_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
