# Generated by Django 2.2.3 on 2019-08-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190810_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='user_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
