# Generated by Django 2.2.3 on 2019-08-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190810_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='typ',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='support',
            name='user_id',
        ),
    ]
