# Generated by Django 2.2.1 on 2019-08-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_detect_list'),
        ('myapp', '0013_auto_20190810_0317'),
    ]

    operations = [
    ]
