# Generated by Django 2.2.3 on 2019-08-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
