# Generated by Django 2.2.3 on 2019-08-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('state', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('feature', models.TextField()),
                ('user', models.CharField(max_length=30)),
            ],
        ),
    ]
